WebApplication10/Models/ErrorViewModel.cs
namespace WebApplication10.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebApplication10/Models/Product.cs
using System.Runtime.Serialization;

namespace WebApplication10.Models
{
    public class ProductViewModel
    {
        public string Size { get; set; } = "";
        public string Name { get; set; } = "";
        public int Count { get; set; }

        public ProductViewModel() { }
    }
}

WebApplication10/Models/User.cs
namespace WebApplication10.Models
{
    public class UserViewModel
    {

        public string Password { get; set; } = "";
        public string Email { get; set; } = "";
        public int Age { get; set; }
    }
}

WebApplication10/Controllers/AppController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;
using WebApplication10.Models;

namespace WebApplication10.Controllers
{
    public class AppController : Controller
    {

        public IActionResult Register()
        {
            return View();
        }


        public IActionResult Small()
        {
            return View();
        }

        public IActionResult Error()
        {
            return View();
        }

        public IActionResult ProductForms()
        {
            int? numProd = TempData["ProducForms"] as int?;
            ViewData["NumProd"] = numProd;
            return View();
        }

        public IActionResult ProductsNumber()
        {
            return View();
        }

        public IActionResult Products()
        {
            string? productsSerealized = TempData["ProductsInfo"] as string;
            if (productsSerealized == null)
            {
                return BadRequest("Order data not found.");
            }
            List<ProductViewModel> products = JsonSerializer.Deserialize<List<ProductViewModel>>(productsSerealized);
            ViewData["Products"] = products;
            return View();
        }

        [HttpPost]
        public IActionResult Register(UserViewModel user)
        {
            if (user.Age < 16)
            {
                return RedirectToAction(nameof(Small));
            }
            return RedirectToAction(nameof(ProductsNumber));
        }


        [HttpPost]
        public IActionResult ProductsNumber(int numProd)
        {
            if (numProd <= 0)
            {
                return RedirectToAction(nameof(Error));
            }
            TempData["ProducForms"] = numProd;
            return RedirectToAction(nameof(ProductForms));
        }

        [HttpPost]
        public IActionResult FormResult(List<ProductViewModel> products)
        {
            foreach (ProductViewModel product in products)
            {
                Console.WriteLine("///");
                Console.WriteLine(product.Name);
            }
            string serealized = JsonSerializer.Serialize(products);
            TempData["ProductsInfo"] = serealized;
            return RedirectToAction(nameof(Products));
        }
    }
}

WebApplication10/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebApplication10.Models;

namespace WebApplication10.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebApplication10/Views/App/ProductForms.cshtml
@{
    ViewData["Title"] = "Enter your order";
    int? numProd = ViewData["NumProd"] as int?;
}

@model List<ProductViewModel>

<h1>@ViewData["Title"]</h1>

@using (Html.BeginForm("FormResult", "App", FormMethod.Post, new { id = "checkoutForm" }))
{
    @for (int i = 0; i < numProd; i++)
    {
        <div class="text-center" style="border: 1px solid black; margin-top:15px; padding:10px">
            <div  style="display:flex; align-items:center; justify-content:center; flex-direction:column; gap:15px">
                <div style="width:270px; display:flex; justify-content:space-between; align-items:center">
                    <label for="Size" style="text-align:left">
                        Size of pizza
                    </label>
                    <input  name="Products[@i].Size" />
                </div>
                <div style="width:270px; display:flex; justify-content:space-between; align-items:center">
                    <label for="Name" style="text-align:left">
                        Name of pizza
                    </label>
                    <input name="Products[@i].Name" type="text" />
                </div>
                <div style="width:270px; display:flex; justify-content:space-between; align-items:center">
                    <label for="Count" style="text-align:left">
                        Count of pizza
                    </label>
                    <input name="Products[@i].Count" />
                </div>
            </div>
        </div>
    }
    <button type="submit">Submit</button>
}

WebApplication10/Views/App/Products.cshtml
@{
    ViewData["Title"] = "Products";
    List < ProductViewModel >? products = ViewData["Products"] as List<ProductViewModel>;
}
<h1>@ViewData["Title"]</h1>



<table>
    <tr>
            <thead>Size</thead>
            <thead>Name</thead>
            <thead>Count</thead>
    </tr>
    @foreach (var item in products)
    {
        <tr>
            <td>@item.Size</td>
            <td>@item.Name</td>
            <td>@item.Count</td>
        </tr>
    }

</table>

WebApplication10/Views/App/ProductsNumber.cshtml
@{
    ViewData["Title"] = "Number of products";
}
<h1>@ViewData["Title"]</h1>

<div class="text-center">
    <form method="post" action="https://localhost:7183/App/ProductsNumber" style="display:flex; align-items:center; justify-content:center; flex-direction:column; gap:15px">
        <div style="width:290px; display:flex; justify-content:space-between; align-items:center">
            <label for="numProd" style="text-align:left">
                Number of products
            </label>
            <input name="numProd" />
        </div>
        <button type="submit">Submit</button>
    </form>
</div>

WebApplication10/Views/App/Register.cshtml
@{
    ViewData["Title"] = "Registration Page";
}
@model UserViewModel

<h1>@ViewData["Title"]</h1>

<div class="text-center">
    <form method="post" action="https://localhost:7183/App/Register" style="display:flex; align-items:center; justify-content:center; flex-direction:column; gap:15px">
        <div style="width:270px; display:flex; justify-content:space-between; align-items:center">
        <label for="email" style="text-align:left">
            E-mail
        </label>
        <input name="email"/>
        </div>
        <div style="width:270px; display:flex; justify-content:space-between; align-items:center">
        <label for="password" style="text-align:left">
            Password
        </label>
        <input name="password" type="password" />
        </div>
        <div style="width:270px; display:flex; justify-content:space-between; align-items:center">
        <label for="count" style="text-align:left">
            Age
        </label>
        <input name="age" />
        </div>
        <button type="submit">Submit</button>
    </form>
</div>

WebApplication10/Views/App/Small.cshtml
@{
    ViewData["Title"] = "Too Small";
}
<h1>@ViewData["Title"]</h1>

<p>You are too small for this page</p>

WebApplication10/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

WebApplication10/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication10</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplication10.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApplication10</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="App" asp-action="Register">Register</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - WebApplication10 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>